### ISSUE TITLE
Unable to Use this provider with 2FA Enabled

### ISSUE THREAD

**Issue by a16mc** [techBeck03/terraform-provider-guacamole#10]
### Terraform Version
Terraform v1.1.3

### Expected Behavior
I am hoping to be able to run this while having 2FA enabled. 

### Actual Behavior
I have been having to run a playbook to disable 2FA, run the code, then reenable 2FA.

**Comment by techBeck03** [comment]
I don't think terraform as a tool is really meant to support interactive logins. With that in mind, would it help if I add the ability to supply the auth token as an alternative to username/password for provider authentication?  This would allow you to externally login to guac using dfa and supply the token issued. Thanks!

**Comment by a16mc** [comment]
That would be awesome!

**Comment by techBeck03** [comment]
@a16mc I released a new version of the provider with the proposed workaround.  Let me know if this works for you.  Thanks
