### ISSUE TITLE
Support connection group tree larger than 2 sub-groups with non-unique structure.

### ISSUE THREAD

**Issue by JohanLeirnes** [techBeck03/terraform-provider-guacamole#9]
### Terraform Version
v1.2.7

### Affected Resource(s)
- guacamole_connection_group

### Expected Behavior
'path' should be absolute path so that it is always unique.
Each 'path' should return the specified id in the tree

### Actual Behavior
Scenario:
tree: 
```
ROOT
├ A
│ └ B
│   └ C
│     └ connection-1
└ B
  └ B
    └ C
      └ connection-2
```

When creating the two connections the parent_id returns two different ids at random because 'path' is 'B/C' in both cases.

**Comment by JohanLeirnes** [comment]
@techBeck03

Have you had time to look into this?

**Comment by techBeck03** [comment]
I'll try to get a fix out this week. Thanks!

**Comment by techBeck03** [comment]
@JohanLeirnes Sorry for the delay but i finally released a fix for this issue.  Please let me know if this works for you.
